### ISSUE TITLE
Full Chunk-based Computing Roadmap

### ISSUE THREAD

**Issue by skyzh** [skyzh/tikv#2]
RFC: https://github.com/tikv/rfcs/pull/43/

Issue: https://github.com/tikv/tikv/issues/7724

## Transition Phase
- [x] modify `rpn_fn` to use `Option<&T>`: make `rpn_fn` transform `Option` with `as_ref()`. (https://github.com/skyzh/tikv/pull/3 + https://github.com/tikv/tikv/pull/7979)
- [x] change `Option<&Json>` and `Option<&Bytes>` to `JsonRef` and `ByteRef` (Drafts on https://github.com/skyzh/tikv/pull/7 + https://github.com/tikv/tikv/pull/8019)
- [x] refactor internally to use `ScalarValueRef(&T)` and `VectorArg(&T)` (#8 + https://github.com/tikv/tikv/pull/8070)
- [x] <del>implement lifetime for `rpn_fn` (#8)</del>
- [x] implement a `NotChunkedVec` which is a wrapper of `Vec<Option<T>>` but implements `ChunkedVec` interface, as well as refactor `aggr` and `executor` (#9 + https://github.com/tikv/tikv/pull/8141)
## Test Branch
- [x] Implement `JSONWriter`, `ByteWriter`.
- [x] Implement `JsonRef` and `ByteRef` (Drafts on https://github.com/skyzh/tikv/pull/6)
## New `ChunkedVec` Phase
- [x] switch `NotChunkedVec` to `ChunkedVec` (https://github.com/skyzh/tikv/pull/12 + https://github.com/tikv/tikv/pull/8214)
- [x] implement `ChunkedVecBytes` (https://github.com/tikv/tikv/pull/8239)
- [x] implement `ChunkedVecJson` (https://github.com/tikv/tikv/pull/8239)
- [x] support non-nullable `rpn_fn` (https://github.com/tikv/tikv/pull/8280, https://github.com/tikv/tikv/pull/8297)
- [x] direct copy optimization (https://github.com/tikv/tikv/pull/8300, https://github.com/tikv/tikv/pull/8305)
- [x] Writer / Guard support (https://github.com/tikv/tikv/pull/8312)
- [x] Merge Nulls (https://github.com/tikv/tikv/pull/8345)

This two phases will be worked in parallel.

**Comment by skyzh** [comment]
Some Examples

```rust
pub struct IntWriter <'a> {
    inner: &'a mut Vec<Option<u64>>
}

pub struct IntWriterGuard <'a> {
    inner: &'a mut Vec<Option<u64>>
}

impl <'a> IntWriter <'a> {
    pub fn write(self, x: u64) -> IntWriterGuard<'a> {
        self.inner.push(Some(x));
        IntWriterGuard { inner: self.inner }
    }

    pub fn into_inner(self) -> &'a mut Vec<Option<u64>> {
        self.inner
    }
}

impl <'a> IntWriterGuard <'a> {
    pub fn into_inner(self) -> &'a mut Vec<Option<u64>> {
        self.inner
    }
}

pub trait AsIntWriter {
    fn to_writer(&mut self) -> IntWriter;
}

impl AsIntWriter for Vec<Option<u64>> {
    fn to_writer(&mut self) -> IntWriter {
        IntWriter { inner: self }
    }
}
```
