### ISSUE TITLE
Gain basic understanding of the Co-processor framework

### ISSUE THREAD

**Issue by skyzh** [skyzh/tikv#4]
Planned Due @ June 1

## Task List
- [x] Chunk format in TiKV and TiDB
- [x] `rpn_fn` implementation
- [x] It seems that `Chunk` is used nowhere in TiKV :(
- [x] Read eval of `rpn_fn`
- [x] Summarize required functionalities of `ChunkedVec`

## Q&A

Q: How to implement `Chunk` with multiple columns of different type?
A: Should deprecate Chunk

Q: What's `downcast_meta`, and how did the example in `rpn_fn` document work?
A: Maybe there're clues in `impl_compare_in`.

Q: Same Arg may implement multiple traits. How to call correct function?

## Notes

`ChunkedVec` is something that:

* Like `Vec`
* Optimize store of `null` values
* Will be used in `rpn_fn` calculation

**Currently, data processing is using `Vec<Option<T>>`. What we need to do is to migrate to use TiDB-like `Chunk` format in this process.**
